site_name: Python DESFire
repo_url: https://github.com/waza-ari/python-desfire
docs_dir: docs
site_dir: public
theme:
  name: "material"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            separate_signature: true
            unwrap_annotated: true
            show_signature_annotations: true

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 4
      permalink: true
      title: Page contents

nav:
  - index.md
  - Supported Commands: supported-commands.md
  - Using this Library: usage.md
  - Key Diversification: key-diversification.md
  - "API Reference":
    - "Card Commands": api/desfire.md
    - "Key Handling": api/key.md
    - "Key Diversification": api/diversification.md
    - "Utility Methods": api/utility.md
    - "ENUMs / Schemas":
      - "Communication Mode": api/enums/communication_mode.md
      - "File Permissions": api/enums/file_permissions.md
      - "File Settings": api/enums/file_settings.md
      - "Key Settings": api/enums/key_settings.md

watch:
  - docs
  - src
