version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  lint:
    cmds:
      - poetry run ruff check src --fix
      - poetry run ruff format src
      - poetry run mypy src

  test:
    cmds:
      - poetry run pytest

  docs:
    cmds:
      - poetry run mkdocs serve
