name: Package Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "python-desfire"
          repository_url: "https://test.pypi.org/legacy/"
  release:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_name: "python-desfire"
